#!/bin/sh

name="ntrip_daemon"
cmd="ntrip_daemon --settings"
dir="/"
user="ntripd"

setup_permissions() {

  mkdir -p /var/run/ntrip/control
  touch /var/run/ntrip/control/socket
  chown $user:$user /var/run/ntrip/control/socket

  # Sticky bit is set so that ntrip_daemon can create it's
  #   control socket but (and allow others to write to it)
  #   but not delete the control socket.
  chmod 1775 /var/run/ntrip/control

  touch /var/run/ntrip/enabled
  chown $user:$user /var/run/ntrip/enabled
  chmod 0644 /var/run/ntrip/enabled

  chown -R $user:$user /var/run/ntrip
}

source /etc/init.d/template_process.inc.sh
