#!/bin/ash

depmod -a

modprobe usbcore
modprobe usb_common
modprobe usb_storage

modprobe udc_core
modprobe udc_xilinx

modprobe ci_hdrc
modprobe ci_hdrc_usb2
modprobe ehci_hcd

modprobe usbserial
modprobe cdc_acm
modprobe libcomposite
modprobe usb_f_acm
#modprobe usb_f_ecm
modprobe u_serial
#modprobe usb_f_rndis
#modprobe u_ether

#modprobe usbhid

modprobe input_leds
modprobe led_class
modprobe leds_gpio

modprobe pl330

modprobe slhc
modprobe ppp_generic
modprobe bsd_comp
modprobe ppp_async
modprobe ppp_deflate

modprobe mmc_core
modprobe mmc_block

modprobe of_xilinx_wdt
modprobe cadence_wdt

modprobe rtc_m41t80
#modprobe cpufreq_performance
#modprobe cpufreq_ondemand
#modprobe cpufreq_stats
#modprobe cpufreq_powersave
#modprobe cpufreq_conservative

modprobe uio
modprobe uio_pdrv_genirq
modprobe uio_xilinx_apm

modprobe cn

#modprobe hwmon

modprobe xilinx_can
modprobe can_dev
modprobe can
modprobe can_raw
modprobe can_bcm
modprobe can_gw

modprobe unix
modprobe ipv6
