#!/bin/sh

name="piksi_leds"
pid=/var/run/${name}.pid

start() {
    modprobe input_leds
    modprobe led_class
    modprobe leds_gpio

    piksi_leds &
    echo $! >${pid}
}

stop() {
    kill $(cat ${pid})
}

source /etc/init.d/template_command.inc.sh
