#!/bin/sh
#
# Coldplug modules....
#

start() {

    modprobe xilinx_can
    modprobe can_dev
    modprobe can
    modprobe can_raw
    modprobe can_bcm
    modprobe can_gw

	  echo "Coldplug modules..."
	  # coldplug modules
	  find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
}

case "$1" in
  start) start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
