#!/bin/sh

mode="$1"; shift

log_tag=update_eth0_config
source /etc/init.d/logging.sh

setup_loggers

if [[ "$mode" == "static" ]]; then
  ip_addr="$1"; shift
  netmask="$1"; shift
  gateway="$1"; shift
fi

interfaces=/etc/network/interfaces

interfaces_tmp=$(mktemp)
trap "rm -f $interfaces_tmp; cleanup_loggers; exit 0" EXIT TERM STOP HUP

if [[ "$mode" == "dhcp" ]]; then
  echo "iface eth0 inet dhcp" >$interfaces_tmp
elif [[ "$mode" == "static" ]]; then
  cat >$interfaces_tmp <<EOF
iface eth0 inet static
	address $ip_addr
	netmask $netmask
	gateway $gateway
EOF
else
  loge "Unknown network mode"
fi

if diff -q $interfaces_tmp $interfaces &>/dev/null; then

  logi "Interface config unchanged, exiting"

  exit 0
fi

logi "Interface config changed, reconfiguring..."

/etc/init.d/S83ifplugd stop
ifdown -f eth0

mv $interfaces_tmp $interfaces
chmod 0644 $interfaces

/etc/init.d/S83ifplugd start
