#!/bin/sh

daemon_name=external

fileio_dir=/data/
persist_dir=/persistent/
media_dir=/media/

control_dir="/var/run/sbp_fileio_${daemon_name}"

dir_perm=0755
file_perm=0644

name="sbp_fileio_daemon_${daemon_name}"
cmd="sbp_fileio_daemon \
--name ${daemon_name} \
--pub ipc:///var/run/sockets/fileio_${daemon_name}.sub \
--sub ipc:///var/run/sockets/fileio_${daemon_name}.pub \
--basedir $fileio_dir \
--basedir $persist_dir \
--basedir $media_dir \
--imageset"

dir="/"
user="fileio"

setup_permissions()
{
  configure_dir_resource_rec "$user" "$fileio_dir"  "$dir_perm" "$file_perm"
  configure_dir_resource_rec "$user" "$persist_dir" "$dir_perm" "$file_perm"
  configure_dir_resource_rec "$user" "$media_dir"   "$dir_perm" "$file_perm"

  configure_dir_resource "$user" "$control_dir" "$dir_perm"
}

export name cmd dir user

# shellcheck disable=SC1091
. /etc/init.d/template_runsv.inc.sh
