#!/bin/sh

daemon_name=external

fileio_dir=/data/
persist_dir=/persistent/
media_dir=/media/

control_dir="/var/run/sbp_fileio_${daemon_name}"

dir_perm=0755
file_perm=0644

## The ports below must be specified in matched pairs
## and must match up with the ports specified in ports.c
## of ports_daemon.

name="sbp_fileio_daemon_${daemon_name}"
cmd="sbp_fileio_daemon \
--name ${daemon_name} \
\
--pub-s ipc:///var/run/sockets/fileio/tcp_server0.pub \
--sub-s ipc:///var/run/sockets/fileio/tcp_server0.sub \
\
--pub-s ipc:///var/run/sockets/fileio/tcp_server1.pub \
--sub-s ipc:///var/run/sockets/fileio/tcp_server1.sub \
\
--pub-s ipc:///var/run/sockets/fileio/usb0.pub \
--sub-s ipc:///var/run/sockets/fileio/usb0.sub \
\
--pub-s ipc:///var/run/sockets/fileio/usb2.pub \
--sub-s ipc:///var/run/sockets/fileio/usb2.sub \
\
--pub-s ipc:///var/run/sockets/fileio/uart0.pub \
--sub-s ipc:///var/run/sockets/fileio/uart0.sub \
\
--pub-s ipc:///var/run/sockets/fileio/uart1.pub \
--sub-s ipc:///var/run/sockets/fileio/uart1.sub \
\
--basedir $fileio_dir \
--basedir $persist_dir \
--basedir $media_dir \
--imageset"

dir="/"
user="fileio"

setup_permissions()
{
  configure_dir_resource_rec "$user" "$fileio_dir"  "$dir_perm" "$file_perm"
  configure_dir_resource_rec "$user" "$persist_dir" "$dir_perm" "$file_perm"
  configure_dir_resource_rec "$user" "$media_dir"   "$dir_perm" "$file_perm"

  configure_dir_resource "$user" "$control_dir" "$dir_perm"
}

export name cmd dir user

# shellcheck disable=SC1091
. /etc/init.d/template_runsv.inc.sh
