#!/bin/sh

name="ota_daemon"
cmd="ota_daemon --settings"
dir="/"
user="otad"

setup_permissions()
{
  mkdir -p /upgrade_data/ota
  chown -R ${user}:${user} /upgrade_data/ota

  # Setup runit dir dynamic services
  mkdir -p /var/run/${name}/sv
  chown -R ${user}:${user} /var/run/${name}
}

source /etc/init.d/template_runsv.inc.sh
