#!/bin/sh

name="starling_daemon"
cmd="starlingd"
dir="/"
user="strlngd"

log_tag=$name # required by logging.sh
source /etc/init.d/logging.sh

starling_daemon_enabled=$(cat /persistent/flags/starling_on_linux 2>/dev/null)

if [[ "$starling_daemon_enabled" != "1" ]]; then
  logi --sbp "Starling daemon not enabled"
  exit 0
fi

logi --sbp "Starling daemon enabled"
source /etc/init.d/template_runsv.inc.sh
