#!/bin/sh

source /etc/init.d/common.sh

name="bcm_wrapper"
cmd="bcm_wrapper -p /dev/gc/a/pwr_en -g /dev/gc/a/nstandby /dev/ttymxc4"
dir="/"
user="bcmd"

export name cmd dir user

setup_permissions()
{
  chown $user:$user /dev/ttymxc4
  chown --dereference $user:$user /dev/gc/a/nstandby
}

. /etc/init.d/template_runsv.inc.sh
