#!/bin/sh

AUX_MODEM_PORT="/dev/ttyACM3"
name="cell_modem_daemon"
cmd="cell_modem_daemon --serial-port $AUX_MODEM_PORT"
dir="/"
user="celld"

setup_permissions() {
    chown $user:$user $AUX_MODEM_PORT
}

source /etc/init.d/template_process.inc.sh
