#!/bin/sh

name=ports_daemon
service=${name}_runsvdir
user=portsd

# enable job control
set -m

# kill -$pid will kill the whole process group
trap 'kill -HUP -$pid && kill -TERM -$pid' HUP TERM

rm -f /var/run/${service}.stderr
mkfifo /var/run/${service}.stderr

rm -f /var/run/${service}.stdout
mkfifo /var/run/${service}.stdout

logger -t ${service} -p info </var/run/${service}.stdout &
logger -t ${service} -p info </var/run/${service}.stderr &

chpst -u ${user} runsvdir /var/run/${name}/sv &

pid=$!
wait $pid
