#!/bin/sh

name="endpoint_router_j1939"
cmd="endpoint_router --name j1939 -f /etc/endpoint_router/j1939_router.yml"
dir="/"
user="rt_j1939"
priority="-19"

setup_permissions()
{
  add_service_user $user
}

source /etc/init.d/template_runsv.inc.sh
