#!/bin/sh
#
# initialize factory data
#

case "$1" in
  start)
  mkdir -p /factory
  if [ ! -e /factory/uuid ]; then
    if [ -e /media/mmcblk0p1/uuid ]; then
      cat /media/mmcblk0p1/uuid | sed "s/-//g" > /factory/uuid
    else
      uuidgen | sed "s/-//g" > /factory/uuid
    fi
  fi
  ;;
  stop)
  ;;
  restart|reload)
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit $?
