#!/bin/sh

name="piksi_fpga"

start() {
  bit="piksi_fpga.bit"
  if [ -f /lib/firmware/"$bit" ]; then
    tries=1
    while [ $tries -le 3 ]; do
      echo "$bit" > /sys/devices/platform/pcap/fpga_manager/fpga0/firmware
      prog_done=`cat /sys/devices/platform/pcap/fpga_manager/fpga0/state`
      if [ "$prog_done" = "operating" ]; then
        break
      else
        echo "ERROR: FPGA configuration failed" | logger
        echo "ERROR: FPGA configuration failed" | sbp_log --error
        echo "ERROR: FPGA configuration failed"
      fi
      tries=`expr $tries + 1`
    done
  else
    echo "ERROR: FPGA bitstream not found" | logger
    echo "ERROR: FPGA bitstream not found" | sbp_log --error
    echo "ERROR: FPGA bitstream not found"
  fi
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh

