#!/bin/sh

export name="resource_monitor"
export cmd="resource_monitor"
export dir="/"
export user="resmond"
export priority="20"

setup_permissions()
{
  # Add the network admin capability
  /usr/sbin/setcap cap_net_admin+ep /usr/bin/extrace

  # Setup runit dir dynamic services
  mkdir -p /var/run/${name}/sv
  chown -R ${user}:${user} /var/run/${name}
}

source /etc/init.d/template_runsv.inc.sh
