#!/bin/sh

name="skylark_daemon"
cmd="skylark_daemon --settings"
dir="/"
user="skylark_daemon"

setup_permissions() {

  mkdir -p /var/run/skylark/control
  chown -R skylark_daemon:skylark_daemon /var/run/skylark

  # Sticky bit is set so that skylark_daemon can create it's
  #   control socket but (and allow others to write to it)
  #   but not delete the control socket.
  chmod 1775 /var/run/skylark/control

  touch /var/run/skylark/enabled
  chown skylark_daemon:skylark_daemon /var/run/skylark/enabled
  chmod 0644 /var/run/skylark/enabled
}

source /etc/init.d/template_process.inc.sh
