#!/bin/sh

name="skylark_daemon"
cmd="skylark_daemon --settings"
dir="/"
user="skylarkd"

setup_permissions() {

  mkdir -p /var/run/skylark/control
  chown -R $user:$user /var/run/skylark

  chown $user:$user /etc/skylark_upload_filter_out_config

  # Sticky bit is set so that skylark_daemon can create it's
  #   control socket but (and allow others to write to it)
  #   but not delete the control socket.
  chmod 1775 /var/run/skylark/control

  touch /var/run/skylark/enabled
  chown $user:$user /var/run/skylark/enabled
  chmod 0644 /var/run/skylark/enabled
}

source /etc/init.d/template_process.inc.sh
