#!/bin/sh

name=runit

run_dir=/var/service

stdout=/var/run/fifos/$name.stdout
stderr=/var/run/fifos/$name.stderr

started_socket=/var/run/runit.socket

cleanup()
{
  rm $stdout
  rm $stderr

  kill -HUP "$pid" "$stderr_pid" "$stdout_pid"
  kill -TERM "$pid" "$stderr_pid" "$stdout_pid"
}

trap 'cleanup; exit 0' HUP TERM EXIT

rm -f $stdout $stderr
mkfifo $stdout $stderr

chpst -u pk_log logger -t $name -p daemon.info <$stdout &
stdout_pid=$!

chpst -u pk_log logger -t $name -p daemon.err  <$stderr &
stderr_pid=$!

runsvdir $run_dir 1>$stdout 2>$stderr &
echo y | socat -u STDIN "UNIX-CONNECT:$started_socket"

pid=$!
wait $pid
