#!/bin/sh

# shellcheck disable=SC1091

export name="reboot_logger"          # required by template_command.inc.sh

export log_tag=$name                 # required by logging.sh
. /etc/init.d/logging.sh

start() {
  :
}

stop() {
  logi --sbp "System rebooting..."
}

. /etc/init.d/template_command.inc.sh
