#!bin/sh
#
# initialize flags
#

starling_daemon_enabled=$(query_config --section experimental_flags --key starling_on_linux)

if [[ "$starling_daemon_enabled" == "True" ]]; then
  echo "1" > /etc/flags/starling_on_linux
elif [[ "$starling_daemon_enabled" == "False" ]]; then
  echo "0" > /etc/flags/starling_on_linux
fi

can_ports_enabled=$(query_config --section experimental_flags --key can_ports)

if [[ "$can_ports_enabled" == "True" ]]; then
  echo "1" > /etc/flags/can_ports
elif [[ "$can_ports_enabled" == "False" ]]; then
  echo "0" > /etc/flags/can_ports
fi

# used by PFWP to determine IMU default
if detect_piksi_ins; then
  echo "1" > /etc/flags/ins_active
else
  echo "0" > /etc/flags/ins_active
fi

