#!bin/sh
#
# initialize flags
#

starling_daemon_enabled=$(query_config --section experimental_flags --key starling_on_linux)

if [[ "$starling_daemon_enabled" == "True" ]]; then
  echo "1" > /etc/flags/starling_on_linux
fi

can_ports_enabled=$(query_config --section experimental_flags --key can_ports)

if [[ "$can_ports_enabled" == "True" ]]; then
  echo "1" > /etc/flags/can_ports
fi

