#!/bin/sh

# shellcheck disable=SC1091,SC2169,SC2039

source /etc/init.d/common.sh

export name="endpoint_router_sbp"
export dir="/"
export user="rt_sbp"
export priority="-20"

setup_permissions()
{
  add_service_user $user
}

starling_daemon_enabled=$(query_config --section experimental_flags --key starling_on_linux)

if detect_piksi_ins; then
  router_config="/etc/endpoint_router/sbp_router_smoothpose.yml"
elif [[ "$starling_daemon_enabled" == "True" ]]; then
  router_config="/etc/endpoint_router/sbp_router_starling.yml"
else
  router_config="/etc/endpoint_router/sbp_router.yml"
fi

export cmd="endpoint_router --sbp --name sbp -f $router_config"

source /etc/init.d/template_runsv.inc.sh
