#!/bin/sh

name="endpoint_router_sbp"
dir="/"
user="rt_sbp"
priority="-20"

setup_permissions()
{
  add_service_user $user
}

if grep -q "output_mode=Loosely Coupled" /persistent/config.ini; then
  router_config="/etc/endpoint_router/sbp_router_smoothpose.yml"
else
  router_config="/etc/endpoint_router/sbp_router.yml"
fi

cmd="endpoint_router --sbp --name sbp -f $router_config"

source /etc/init.d/template_runsv.inc.sh
