#!/bin/sh

name="sbp_settings_daemon"
cmd="sbp_settings_daemon"
dir="/"
user="configd"

SETTINGS_FILE="/persistent/config.ini"

setup_permissions()
{
  configure_file_resource $user $SETTINGS_FILE 0600
}

source /etc/init.d/template_runsv.inc.sh
