#!/bin/sh

FILEIO_DIR=/data/
PERSIST_DIR=/persistent/
MEDIA_DIR=/media/

name="sbp_fileio_daemon_external"
cmd="sbp_fileio_daemon \
-p 'ipc:///var/run/sockets/fileio_external.sub' \
-s 'ipc:///var/run/sockets/fileio_external.pub' \
--basedir $FILEIO_DIR \
--basedir $PERSIST_DIR \
--basedir $MEDIA_DIR \
--imageset"

dir="/"
user="fio_ex"

setup_permissions()
{
  configure_dir_resource $user $FILEIO_DIR 0700
}

source /etc/init.d/template_runsv.inc.sh
