#!/bin/sh

name="health_daemon"
cmd="health_daemon"
dir="/"
user="healthd"

setup_permissions() {
  mkdir -p /var/run/health
  echo '0' > /var/run/health/gps_time_available
  configure_file_resource $user /var/run/health/gps_time_available 0644
}

source /etc/init.d/template_runsv.inc.sh
