#!/bin/sh

name="piksi_leds"
cmd="piksi_leds"
dir="/"
user="ledd"

DURO_EEPROM_PATH="/sys/devices/soc0/amba/e0005000.i2c/i2c-1/1-0050/eeprom"
DURO_EEPROM_CFG_PATH="/cfg/duro_eeprom"
EEPROM_RETRY_DELAY=0.15 # seconds

log()
{
  local priority=$1; shift
  logger -s -t $name -p $priority
}

try_eeprom_copy()
{
  dd if=$DURO_EEPROM_PATH bs=1 count=6 of=$DURO_EEPROM_CFG_PATH &>/dev/null
}

copy_duro_eeprom()
{
  local retries=5
  if [ -f "$DURO_EEPROM_PATH" ]; then
    while [ $retries -ge 0 ]; do
      if try_eeprom_copy; then
        chmod 0644 "$DURO_EEPROM_CFG_PATH"
        break;
      fi
      echo "Failed to copy Duro EEPROM, ${retries} retries left..." | log err
      retries=$(($retries-1))
      sleep $EEPROM_RETRY_DELAY
    done
  else
    echo "No 'Duro' EEPROM path present on this device..." | log warn
  fi
}

setup_permissions()
{
  chown $user:$user /dev/i2c-0
  chown $user:$user /dev/i2c-1

  copy_duro_eeprom
}

source /etc/init.d/template_runsv.inc.sh
