#!/bin/sh
#
# Coldplug modules....
#

case "$1" in
  start)
	echo "Coldplug modules..."
	# coldplug modules
	find /sys/ -name modalias | while read MODALIAS;
	do
		modprobe -abq `cat "$MODALIAS"`
	done
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
