#!bin/sh
#
# reset boot counters
#

export name="reset_boot_counter"

export log_tag=$name
source /etc/init.d/logging.sh

source /etc/init.d/common.sh

initialize_uboot_environment()
{
  fw_setenv env_version_major 0
  fw_setenv env_version_minor 1
  fw_setenv env_version_minor_minor 0
  fw_setenv pre_boot_counter 0
  fw_setenv post_boot_counter 0
  fw_setenv increment_boot_counter "setexpr pre_boot_counter \${pre_boot_counter} + 1; saveenv;"
  fw_setenv pre_load_tasks "run increment_boot_counter;"
  fw_setenv bootcmd "run pre_load_tasks; run fpgaload; run sdboot; run netboot;"
}

if fw_printenv env_version_major; then
  env_version_major=$(fw_printenv -n env_version_major)
  env_version_minor=$(fw_printenv -n env_version_minor)
  env_version_minor_minor=$(fw_printenv -n env_version_minor_minor)

  if [[ $env_version_major -ge 0 && $env_version_minor -ge 1 && $env_version_minor_minor -ge 0 ]]; then
    pre_boot_counter=$(fw_printenv -n pre_boot_counter)
    post_boot_counter=$(fw_printenv -n post_boot_counter)
    if [[ $pre_boot_counter != 1 || $post_boot_counter != 1 ]]; then
      if [[ $pre_boot_counter == 0 ]]; then
        logw --sbp "pre_boot_counter = 0; Have you upgraded dev image?"
      else
        loge --sbp "Unexpected boot counter values! pre_boot_counter: ${pre_boot_counter} post_boot_counter ${post_boot_counter}"
      fi;
    fi;
    logi --sbp "Resetting boot counters... pre_boot_counter: ${pre_boot_counter} post_boot_counter ${post_boot_counter}"
    fw_setenv pre_boot_counter 0
    fw_setenv post_boot_counter 0
  fi;
else
  logi --sbp "No boot counters detected, upgrading U-Boot environment"
  $(initialize_uboot_environment)
fi;
