#!bin/sh
#
# reset boot counters
#

source /etc/init.d/common.sh

upgrade_uboot_environment()
{
  fw_setenv pre_boot_counter 0
  fw_setenv post_boot_counter 0
  fw_setenv increment_boot_counter "setexpr pre_boot_counter \${pre_boot_counter} + 1; saveenv"
  fw_setenv bootcmd "run increment_boot_counter; run fpgaload; run sdboot; run netboot;"
}

if fw_printenv pre_boot_counter; then
  pre_boot_counter=$(fw_printenv -n pre_boot_counter)
  post_boot_counter=$(fw_printenv -n post_boot_counter)
  if [[ $pre_boot_counter == 1 && $post_boot_counter == 1 ]]; then
    fw_setenv pre_boot_counter 0
    fw_setenv post_boot_counter 0
  else
    echo "Warning: Unexpected boot counter values"
    echo "pre_boot_counter: ${pre_boot_counter}"
    echo "post_boot_counter: ${post_boot_counter}"
  fi;
else
  $(upgrade_uboot_environment)
fi;
