#!bin/sh
#
# reset boot counters
#

export name="reset_boot_counter"

export log_tag=$name
source /etc/init.d/logging.sh

source /etc/init.d/common.sh

upgrade_uboot_environment()
{
  fw_setenv pre_boot_counter 0
  fw_setenv post_boot_counter 0
  fw_setenv increment_boot_counter "setexpr pre_boot_counter \${pre_boot_counter} + 1; saveenv"
  fw_setenv bootcmd "run increment_boot_counter; run fpgaload; run sdboot; run netboot;"
}

if fw_printenv pre_boot_counter; then
  pre_boot_counter=$(fw_printenv -n pre_boot_counter)
  post_boot_counter=$(fw_printenv -n post_boot_counter)
  if [[ $pre_boot_counter != 1 || $post_boot_counter != 1 ]]; then
    loge --sbp "Unexpected boot counter values! pre_boot_counter: ${pre_boot_counter} post_boot_counter ${post_boot_counter}"
  fi;
  logi --sbp "Resetting boot counters... pre_boot_counter: ${pre_boot_counter} post_boot_counter ${post_boot_counter}"
  fw_setenv pre_boot_counter 0
  fw_setenv post_boot_counter 0
else
  logi --sbp "No boot counters detected, upgrading U-Boot environment"
  $(upgrade_uboot_environment)
fi;
