#!/usr/bin/env python

import sys
import hashlib

sha1 = hashlib.new('sha1')

if (sys.version_info > (3, 0)):
    sha1.update(sys.stdin.read().encode('utf8'))
else:
    sha1.update(sys.stdin.read())

print(sha1.hexdigest()[:12])
