#!/usr/bin/env bash

set -euo pipefail

CLANG_FORMAT_BINARY=$(command -v clang-format || command -v "clang-format-5.0" || :)
if [ -z "${CLANG_FORMAT_BINARY:-}" ] ; then
  echo "Failed to find clang-format binary in path: $PATH"
  exit 1
fi
CLANG_FORMAT_VERSION=$($CLANG_FORMAT_BINARY --version)
if [[ "$CLANG_FORMAT_VERSION" == *"5.0."* ]]; then
  echo "Formatting C/C++ Sources with $CLANG_FORMAT_VERSION"
else
  echo "Incorrect formatter version ($CLANG_FORMAT_VERSION), expected 5.0"
  exit 1
fi

FIND_COMMAND=$(command -v find)
FIND_BASE_DIR="package"
FIND_ARGS=""
if [[ "$OSTYPE" == "darwin"* ]]; then
  FIND_ARGS="$FIND_ARGS -E"
  FIND_REGEX=".*\\\.\(c\|cc\|cxx\|cpp\|hpp\|h\)$"
else
  FIND_REGEX="'.*\\.\(c\|cc\|cxx\|cpp\|hpp\|h\)$'"
fi
FIND_EXPRESSION="-iregex $FIND_REGEX"
FIND_EXEC="-exec $CLANG_FORMAT_BINARY -i {} +"
eval $FIND_COMMAND $FIND_ARGS $FIND_BASE_DIR $FIND_EXPRESSION $FIND_EXEC

