#!/usr/bin/env python3

'''Verifying access to Piksi INS repositories'''

import os
import sys

from pbr_script_lib import Runner as R
import pbr_script_lib as PBR

PIKSI_INS_REF_REPO = 'git@github.com:swift-nav/piksi_inertial_ipsec_crl.git'
PIKSI_INS_REPO = 'git@github.com:swift-nav/pose_daemon_wrapper.git'


def _main():
    os.chdir(PBR.find_dot_git())
    print('>>> {}...'.format(__doc__))
    sys.stdout.flush()
    (ret, _, _) = R().call('git', 'ls-remote', PIKSI_INS_REF_REPO).exit_code()
    if ret != 0:
        sys.stderr.write(
            '>>> ERROR: access to Piksi INS repo failed: {}\n'.format(PIKSI_INS_REF_REPO))
        sys.exit(1)
    (ret, _, _) = R().call('git', 'ls-remote', PIKSI_INS_REPO).exit_code()
    if ret != 0:
        sys.stderr.write(
            '>>> ERROR: access to Piksi INS repo failed: {}\n'.format(PIKSI_INS_REPO))
        sys.exit(1)


if __name__ == '__main__':
    _main()
