#!/bin/sh

source /etc/init.d/common.sh

name="ports_daemon"
cmd="ports_daemon"
dir="/"
user="portsd"
priority="-17"

setup_permissions() {

  mkdir -p /etc/filter_out_config
  chown -R portsd:portsd /etc/filter_out_config

  chown portsd:portsd /dev/ttyPS0
  chown portsd:portsd /dev/ttyPS1
  chown portsd:portsd $(readlink -f /dev/tty.usb0)
  chown portsd:portsd $(readlink -f /dev/tty.usb2)

  # Setup runit dir dynamic services
  mkdir -p /var/run/${name}/sv
  chown -R ${user}:${user} /var/run/${name}
}

can_ports_enabled=$(cat /etc/flags/can_ports 2>/dev/null)
if [[ "$can_ports_enabled" == "1" ]]; then
  cmd="${cmd} --can-enable"
fi

source /etc/init.d/template_runsv.inc.sh
