#!/bin/sh

METRICS_DIR="/var/log/metrics/"
METRICS_OUTPUT_FILE="/var/log/metrics.json"

name="metrics_daemon"
cmd="metrics_daemon"
dir="/"
user="metricsd"

setup_permissions()	
{	
  configure_file_resource $user $METRICS_OUTPUT_FILE 0644	
  configure_dir_resource $user $METRICS_DIR 1777	
}

source /etc/init.d/template_runsv.inc.sh
