#!/bin/sh

METRICS_OUTPUT_FILE="/var/log/metrics.json"

export name="metrics_daemon"
export cmd="metrics_daemon"
export dir="/"
export user="metricsd"
export priority="20"

setup_permissions()	
{	
  configure_file_resource $user $METRICS_OUTPUT_FILE 0644	
}

source /etc/init.d/template_runsv.inc.sh
