#!/bin/sh

# Enable job control
set -m

mkdir -p /var/service

ls -1 /etc/sv | while read -r svc; do
   ln -sf /etc/sv/$svc /var/service/$svc
done

trap 'kill -HUP -$pid && kill -TERM -$pid' HUP TERM

rm -f /var/run/runit.stderr
mkfifo /var/run/runit.stderr

rm -f /var/run/runit.stdout
mkfifo /var/run/runit.stdout

logger -t runit -p daemon.info </var/run/runit.stdout &
logger -t runit -p daemon.err </var/run/runit.stderr &

runsvdir /var/service 1>/var/run/runit.stdout 2>/var/run/runit.stderr &

pid=$!
wait $pid
