#!/bin/sh

name="usb_gadget"

VENDOR_ID="0x2E69"
PRODUCT_ID="0x1001"
MANUFACTURER="Swift Navigation"
PRODUCT="Piksi Multi"
SERIAL_NUMBER=`cat /factory/uuid`
CONFIGURATION="CDC 2xACM+ECM"

start() {
  # Create gadget
  cd /sys/kernel/config/usb_gadget
  mkdir g1
  cd g1
  echo "$VENDOR_ID" > idVendor
  echo "$PRODUCT_ID" > idProduct

  # Strings
  mkdir strings/0x409
  echo "$MANUFACTURER" > strings/0x409/manufacturer
  echo "$PRODUCT" > strings/0x409/product
  echo "$SERIAL_NUMBER" > strings/0x409/serialnumber

  # Functions
  mkdir functions/acm.GS0
  mkdir functions/acm.GS1
  mkdir functions/ecm.usb0

  # Configurations
  mkdir configs/c.1
  mkdir configs/c.1/strings/0x409
  echo "$CONFIGURATION" > configs/c.1/strings/0x409/configuration
  ln -s functions/acm.GS0 configs/c.1
  ln -s functions/acm.GS1 configs/c.1
  ln -s functions/ecm.usb0 configs/c.1

  # Attach
  for dev in /sys/class/udc/*; do
    echo `basename "$dev"` > UDC
  done
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh
