#!/bin/sh

name="zmq_adapter_gps0"
cmd="zmq_adapter --stdio -s '>tcp://127.0.0.1:44030' | socat pty,raw,link=/dev/gps0 fd:0"
dir="/"
#user="adapter_gps"

#setup_permissions() {
#    chown adapt_gps:adapt_gps /dev/gps0
#}

source /etc/init.d/template_process.inc.sh
