#!/bin/sh

name="dev_boot"

lib_output_path="/lib/firmware"
persistent_output_path="/persistent"
script_path="/root"

copy_from_sd() {
  local sd_path=$1
  local filename=$2
  local output_path=$3
  local sd_file="$sd_path/$filename"
  local output_file="$output_path/$filename"

  if [ -f "$sd_file" ]; then
    rm -f "$output_file"
    echo "Copying $filename from SD card"
    mkdir -p "$output_path"
    cp "$sd_file" "$output_file"

    if [ ! -f "$output_file" ]; then
      echo "ERROR: copy failed for $output_file"
    fi
  fi
}

copy_from_net() {
  local server_ip=$1
  local filename=$2
  local output_path=$3
  local uuid=`cat /factory/uuid`
  local net_file="PK$uuid/$filename"
  local output_file="$output_path/$filename"
  local tmp_file="/tmp/$filename"

  echo "Retrieving $filename from network"
  tftp -g -r "$net_file" -l "$tmp_file" -b 65464 "$server_ip"

  if [ -f "$tmp_file" ]; then
    rm -f "$output_file"
    echo "Copying $filename from network"
    mkdir -p "$output_path"
    cp "$tmp_file" "$output_file"

    if [ ! -f "$output_file" ]; then
      echo "ERROR: copy failed for $output_file"
    fi
  fi
}

start() {
  # Get 'dev_boot' bootarg
  dev_boot=`cat /proc/device-tree/chosen/bootargs |
            sed -n -e 's/^.*dev_boot=\([^ ]*\).*/\1/p'`

  # Delete any firmware files that were already present in the rootfs.
  # In the dev configuration we want to obtain the firmware from the SD card or
  # network and this ensures if these files are not available from the SD card
  # or network we will error out rather than silently falling back to the
  # version present in the rootfs.
  if [ -n "$dev_boot" ]; then
    # If dev_boot is set to something (not null), then we are in the dev
    # configuration
    # DO NOT remove existing persistent settings configuration
    rm -f $lib_output_path/piksi_firmware.elf
    rm -f $lib_output_path/piksi_fpga.bit
  fi

  if [ "$dev_boot" == "sd" ]; then
    # Temporarily load driver and mount SD card
    modprobe sdhci_of_arasan
    sd_path="/media/mmcblk0p1"
    while [ ! -d $sd_path ]; do
      echo "Waiting for SD card to mount..."
      sleep 1
    done

    copy_from_sd $sd_path "piksi_firmware.elf" $lib_output_path
    copy_from_sd $sd_path "piksi_fpga.bit" $lib_output_path
    # Overwrites settings if present on sd card.
    copy_from_sd $sd_path "config.ini" $persistent_output_path
    # Copy custom script if present on sd card.
    copy_from_sd $sd_path "init_script.sh" $script_path

    # Unload driver here so FPGA can be reconfigured, it wil be reloaded
    # by coldplug.
    umount $sd_path
    modprobe -r sdhci_of_arasan
  fi

  if [ "$dev_boot" == "net" ]; then
    # Get server ip from 'ip' bootarg
    server_ip=`cat /proc/device-tree/chosen/bootargs |
               sed -n -e 's/^.*ip=[^:]*:\([^:]*\).*/\1/p'`
    copy_from_net $server_ip "piksi_firmware.elf" $lib_output_path
    copy_from_net $server_ip "piksi_fpga.bit" $lib_output_path
    # Overwrite settings if present on network boot.
    copy_from_net $server_ip "config.ini" $persistent_output_path
    # Download custom script if present on network boot.
    copy_from_net $server_ip "init_script.sh" $script_path
  fi

  # Run custom script if present
  if [ -f "$script_path/init_script.sh" ]; then
    echo "Running init_script.sh"
    sh "$script_path/init_script.sh"
  fi
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh
