#!/bin/sh

export name="endpoint_router_rpmsg_stats"
export cmd="endpoint_router --name rpmsg_stats -f /etc/endpoint_router/rpmsg_stats.yml"
export dir="/"
export user="rt_rpmsg_stats"

setup_permissions()
{
  add_service_user $user
}

source /etc/init.d/template_runsv.inc.sh
