#!/bin/sh

name="endpoint_router_rtcm3"
cmd="endpoint_router --name rtcm3 -f /etc/endpoint_router/rtcm3_router.yml"
dir="/"
user="rt_rtcm3"

setup_permissions()
{
  add_service_user $user
}

source /etc/init.d/template_runsv.inc.sh
