#!/bin/sh

name="zmq_router_sbp"
dir="/"
user=""

if grep -q "output_mode=INS Only" /persistent/config.ini; then
  router_config="/etc/zmq_router/sbp_router_smoothpose.yml"
else
  router_config="/etc/zmq_router/sbp_router.yml"
fi

cmd="zmq_router -f $router_config"

source /etc/init.d/template_process.inc.sh
