#!/bin/sh

name="zmq_router_nmea"
cmd="zmq_router -f /etc/zmq_router/nmea_router.yml"
dir="/"
user="rt_nmea"

setup_permissions()
{
  add_service_user $user
}

source /etc/init.d/template_runsv.inc.sh
