#!/bin/sh

NDB_DIR="/persistent/ndb/"
MTD_FILE="/factory/mtd"

name="sbp_fileio_daemon_firmware"
cmd="sbp_fileio_daemon -p 'ipc:///tmp/tmp.43041' -s 'ipc:///tmp/tmp.43040' --basedir $NDB_DIR --mtd"
dir="/"
user="fio_fw"

setup_permissions()
{
  configure_file_resource $user $MTD_FILE 0640
  configure_dir_resource $user $NDB_DIR 0700
}

source /etc/init.d/template_runsv.inc.sh
