#!/bin/sh

name="sbp_settings_daemon"
cmd="sbp_settings_daemon"
dir="/"
user="configd"

SETTINGS_FILE="/persistent/config.ini"

setup_permissions() {

    touch $SETTINGS_FILE
    chown $user:$user $SETTINGS_FILE
}

source /etc/init.d/template_runsv.inc.sh
