#!/bin/sh

name="sbp_fileio_daemon_firmware"
cmd="sbp_fileio_daemon -p >tcp://localhost:43041 -s >tcp://localhost:43040"
dir="/"
user=""

mkdir -p /persistent/ndb

source /etc/init.d/template_process.inc.sh
