#!/bin/sh

NDB_DIR="/persistent/ndb/"

name="sbp_fileio_daemon_firmware"
cmd="sbp_fileio_daemon -p '>tcp://localhost:43041' -s '>tcp://localhost:43040' --basedir $NDB_DIR --mtd"
dir="/"
user="fio_fw"

setup_permissions()
{
    chmod 0640 /factory/mtd
    chown fio_fw:fio_fw /factory/mtd

    mkdir -p $NDB_DIR
    chown -R $user:$user $NDB_DIR
}

source /etc/init.d/template_runsv.inc.sh
