#!/bin/sh

name="rpmsg_piksi"

start() {
  modprobe virtio_rpmsg_bus
  modprobe rpmsg_piksi
  #chown adapt_rpmsg:adapt_rpmsg /dev/rpmsg_piksi100
  #chown adapt_rpmsg:adapt_rpmsg /dev/rpmsg_piksi101
}

stop() {
  rmmod rpmsg_piksi
  rmmod virtio_rpmsg_bus
}

source /etc/init.d/template_command.inc.sh

