#!/bin/sh

name="endpoint_adapter_rpmsg_piksi101"
cmd="endpoint_adapter --file /dev/rpmsg_piksi101 -p 'ipc:///tmp/tmp.44011' -s 'ipc:///tmp/tmp.44010'"
dir="/"
user="ad_r101"

setup_permissions()
{
  add_service_user $user
  chown $user:$user /dev/rpmsg_piksi101
}

source /etc/init.d/template_runsv.inc.sh

