#!/bin/sh

name="endpoint_adapter_rpmsg_piksi100"
cmd="endpoint_adapter --file /dev/rpmsg_piksi100 -p 'ipc:///tmp/tmp.43011' -s 'ipc:///tmp/tmp.43010'"
dir="/"
user="ad_r100"

setup_permissions()
{
  add_service_user $user
  chown $user:$user /dev/rpmsg_piksi100
}

source /etc/init.d/template_runsv.inc.sh
