#!/bin/sh

name="zmq_adapter_rpmsg_piksi100"
cmd="zmq_adapter --file /dev/rpmsg_piksi100 -p >tcp://127.0.0.1:43011 -s >tcp://127.0.0.1:43010"
dir="/"
user=""

source /etc/init.d/template_process.inc.sh

