#!/bin/sh

name="zmq_adapter_rpmsg_piksi101"
cmd="zmq_adapter --file /dev/rpmsg_piksi101 -p >tcp://127.0.0.1:44011 -s >tcp://127.0.0.1:44010"
dir="/"
user=""

source /etc/init.d/template_process.inc.sh

