#!/bin/sh

name="zmq_adapter_tcp_listen_sbp"
cmd="zmq_adapter --tcp-l 55555 -p >tcp://127.0.0.1:43031 -s >tcp://127.0.0.1:43030 -f sbp"
filter_options="--filter-out sbp --filter-out-config /etc/ethernet_filter_out_config"
dir="/"
user=""

source /etc/init.d/template_process.inc.sh

