#!/bin/sh

name="piksi_fpga"

DEV=fpga0
DEV_FW_PATH=/sys/class/fpga_manager/$DEV/firmware
DEV_STATE=/sys/class/fpga_manager/$DEV/state

is_writing() {
    STATE=`cat $DEV_STATE`

    [ "$STATE" == "firmware request" ] && return 0
    [ "$STATE" == "write init" ] && return 0
    [ "$STATE" == "write" ] && return 0
    [ "$STATE" == "write complete" ] && return 0

    return 1
}

is_operating() {
    STATE=`cat $DEV_STATE`
    [ "$STATE" == "operating" ] && return 0
    return 1
}

start() {
  bit="/lib/firmware/piksi_fpga.bit"
  if [ -f "$bit" ]; then
    tries=1
    while [ $tries -le 3 ]; do
      echo "piksi_fpga.bit" > $DEV_FW_PATH

      while is_writing;
      do
        sleep 0.1
      done

      if is_operating;
      then
        break
      else
        echo "ERROR: FPGA configuration failed" | logger
        echo "ERROR: FPGA configuration failed" | sbp_log --error
        echo "ERROR: FPGA configuration failed"
      fi
      tries=`expr $tries + 1`
    done
  else
    echo "ERROR: FPGA bitstream not found" | logger
    echo "ERROR: FPGA bitstream not found" | sbp_log --error
    echo "ERROR: FPGA bitstream not found"
  fi
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh

