#!/bin/sh

name="piksi_fpga"

start() {
  bit="/lib/firmware/piksi_fpga.bit"
  if [ -f "$bit" ]; then
      modprobe zynq-fpga
      echo "piksi_fpga.bit" > /sys/class/fpga_manager/fpga0/firmware
  else
    echo "ERROR: FPGA bitstream not found" | logger
    echo "ERROR: FPGA bitstream not found" | sbp_log --error
    echo "ERROR: FPGA bitstream not found"
  fi
}

stop() {
    rmmod zynq-fpga
    rmmod fpga-mgr
}

source /etc/init.d/template_command.inc.sh

