#!/bin/sh

name="piksi_fpga"

start() {
  bit="/lib/firmware/piksi_fpga.bit"
  if [ -f "$bit" ]; then
    cat "$bit" > /dev/xdevcfg
    prog_done=`cat /sys/devices/soc0/amba/f8007000.devcfg/prog_done`
    if [ "$prog_done" != "1" ]; then
       echo "ERROR: FPGA configuration failed"
       echo "ERROR: FPGA configuration failed" | SBP_LOG --error
    fi
  else
    echo "ERROR: bitstream not found"
    echo "ERROR: bitstream not found" | SBP_LOG --error
  fi
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh

