#!/bin/sh

start() {
  export FIRMWARE="/media/sda1/PiksiMulti-*.bin"
  export LOGLEVEL="--warn"
  # Sleep briefly to allow the automounting of flashdrive
  sleep 0.5 
  if [ `echo $FIRMWARE | wc -w` != '1' ]; then
    echo 'Upgrade requires exactly one firmware image' | sbp_log $LOGLEVEL
    exit
  fi

  if [ ! -x $FIRMWARE ]; then
    exit
  fi

  echo "New firmware image set detected: `ls $FIRMWARE`" | sbp_log $LOGLEVEL
  echo "Performing upgrade..." | sbp_log $LOGLEVEL
  upgrade_tool --debug $FIRMWARE | sbp_log $LOGLEVEL
  umount /media/sda1
  sync
  while [ 1 ]; do 
    echo "Please remove upgrade media and reboot."  | sbp_log $LOGLEVEL
    sleep 1
  done
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh
