#!/bin/sh

name="network_poll"
cmd="/etc/init.d/network_poll.sh"
dir="/"
user="netpoll"

setup_permissions() {

    addgroup -S $user
    adduser -S -D -H -G $user $user

    touch /var/run/network_available
    chown $user:$user /var/run/network_available
    chmod 0644 /var/run/network_available
}

source /etc/init.d/template_process.inc.sh
