#!/bin/sh

name="network_poll"
cmd="/etc/init.d/network_poll.sh"
dir="/"
user="piksi_sys"

setup_permissions()
{
  configure_file_resource $user /var/run/network_available 0644
  configure_file_resource $user /var/run/network_polling_period 0644
  configure_file_resource $user /var/run/network_polling_retry_period 0644
  configure_file_resource $user /var/run/enable_ping_logging 0644
  configure_file_resource $user /var/log/ping.log 0644
}

source /etc/init.d/template_process.inc.sh
