#!/bin/sh

name="piksi_leds"
cmd="piksi_leds"
dir="/"
user="piksi_leds"

setup_permissions() {
    chown piksi_leds:piksi_leds /dev/i2c-0
    chown piksi_leds:piksi_leds /dev/i2c-1
}

source /etc/init.d/template_process.inc.sh
