#!/bin/sh

name="ifplugd"

start() {
  if [ -f "/etc/ifplugd/ifplugd.action" ]; then
    ifplugd -M -I -t 1
  else
    echo "ERROR: firmware not found"
  fi
}

stop() {
  ifplugd -k
}

source /etc/init.d/template_command.inc.sh
