#!/bin/sh

name="skylark_setup"

start() {
  # Setup DNS
  # TODO (mookerji): Move to a template command?
  rm -f /etc/resolv.conf
  echo "nameserver 8.8.8.8" > /etc/resolv.conf
  date -s '2017-03-09 16:14:00'

  mkfifo /tmp/skylark_download /tmp/skylark_upload
}

stop() {
  :
}

source /etc/init.d/template_command.inc.sh
