#!/bin/sh

name="skylark_zmq_adapter_download_daemon"
cmd="zmq_adapter --file /tmp/skylark_download -f sbp -p >tcp://127.0.0.1:43071 --debug"
dir="/"
user=""

source /etc/init.d/template_process.inc.sh
