#!/bin/sh

name="skylark_download_daemon"
cmd="skylark_download_daemon --pub /tmp/skylark_download --endpoint https://broker.skylark2.swiftnav.com"
dir="/"
user=""

source /etc/init.d/template_process.inc.sh
