#!/bin/sh
#
# initialize skylark data
#

case "$1" in
    start)
        mkfifo /tmp/skylark_download
        mkfifo /tmp/skylark_upload
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
